name: The Unprocessed Queue
tagline: Community management, software development, and emergency response.
description: CTO & community manager for Codidact; software developer and ambulance control room manager.
url: https://artofcode-.github.io
baseurl: ''

permalink: /:slug/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

social:
  github: https://github.com/ArtOfCode-
  discord: https://discord.com/users/355501251947134996

cat_classes:
  '999': bc-green-darkest
  dev: bc-purple-darkest

paginate: 10